### ISSUE TITLE
Ghost flag seems to be ignored

### ISSUE THREAD

**Issue by BonneCW** [BonneCW/GD3D11#14]

**Comment by pkurras** [comment]
The renderer should use "Order-Independent Transparency" as described [here](http://developer.download.nvidia.com/assets/gamedev/docs/OrderIndependentTransparency.pdf). This technique requires more effort but it looks great.

**Comment by Kirides** [comment]
@BonneCW 

- G2: Quarhodron, Rhademes
- Returning 2.0: "Orc Ghosts"
Are now all transparent.
