### ISSUE TITLE
Surface water texture on normal surface textures

### ISSUE THREAD

**Issue by rataje** [BonneCW/GD3D11#37]
Not in Vanilla Gothic 2 NotR
Only with Modifications, especially LHiver 0.98/1.1/1.7 de 
Graphic Card is a Geforce (Gainward) GTX 760

-tested from X15 up to X17.6 
-changed/replaced or removed certain nomalmaps
-checked the LHiver 1.7 mod by myself for problems with water/surface
-installed the game new
-installed drivers with DDU new
-tested with fourteen driver versions bewteen 335.23 (2011) and 425.31 (2019)
-managed the 3D Settings in Control panel in every step above, between every api version 
-checked vcredist, thirty-one versions are installed
-SystemPack versions 1.0, 1.1, 1.6, 1.7 were used
+A complete new installation of windows and did the steps above again
Three days for all investigations. I hope you can fix that if it is by d3d11 or maybe you have a hint for me how i can solve that with nvidia 700 series.
[My "Log.txt" file from last test with driver 425.31 on default control panel 3D settings](https://github.com/BonneCW/GD3D11/files/3099851/Log.txt)

![Unbenannt](https://user-images.githubusercontent.com/49805645/56454214-a7c75180-634d-11e9-8927-dcfd88a430e3.jpg)

regards

**Comment by rataje** [comment]
After a refresh investigation i've found out that the LHE11_DE.mod & LHE17_DE_PATCH.mod files was ignored by gothic 2 in connection to modification textures. So I've disabled and removed all standard/vanilla vdf files and now it was gone! (For the moment^^) I swear i was never forced to rename the Textures.vdf file. I thought the timestamp would do it right. 

Thank you all for your attention anyway.
regards

**Comment by rataje** [comment]
It again there after a level change! Congratulations. I'm totally done with that crap!

**Comment by Kirides** [comment]
@BonneCW 
Should be fixed in the current version.
