### ISSUE TITLE
Fix HAMMEL_BODY hack

### ISSUE THREAD

**Issue by BonneCW** [BonneCW/GD3D11#7]

**Comment by Kirides** [comment]
Ich glaube mal ganz stark, das der Workaround *eigentlich* das Mesh von dem HAMMEL_BODY durch ein SHEEP_BODY ersetzen sollte. Wenn ich mich recht entsinne, hat eine Zuweisung nur ein einzelnes `=`.
`str == "SHEEP_BODY"; ` müsste durch `str = "SHEEP_BODY"; ` ersetzt werden. Dann wird auch das alternative Mesh geladen, ansonsten ist das Schaf unsichtbar.

GothicAPI.cpp
```cpp
if (str == "HAMMEL_BODY") {
    str == "SHEEP_BODY"; // TODO: HAMMEL_BODY seems to have fucked up bones, but only this model! Replace with usual sheep before I fix this
    if (!SkeletalMeshVisuals[str]) {
        RegisteredVobs.erase(vob);
        SkeletalMeshVisuals.erase(str);
        return; // Just don't load it here!
    }
}
```
